const EVENTS_PREFIX = 'events/';

export const GET_EVENTS_REQUEST = `${EVENTS_PREFIX}GET_EVENTS_REQUEST`;
export const GET_EVENTS_OK = `${EVENTS_PREFIX}GET_EVENTS_OK`;
export const GET_EVENTS_ERR = `${EVENTS_PREFIX}GET_EVENTS_ERR`;
