const CONF_PREFIX = 'CONF/';

export const GET_CONF_DATA = `${CONF_PREFIX}GET_CONF_DATA`;
export const GET_CONF_DATA_OK = `${CONF_PREFIX}GET_CONF_DATA_OK`;
export const GET_CONF_DATA_ERR = `${CONF_PREFIX}GET_CONF_DATA_ERR`;
