const CONF_PREFIX = 'conf/';

export const GET_CONF_DATA_REQUEST = `${CONF_PREFIX}GET_CONF_DATA_REQUEST`;
export const GET_CONF_DATA_OK = `${CONF_PREFIX}GET_CONF_DATA_OK`;
export const GET_CONF_DATA_ERR = `${CONF_PREFIX}GET_CONF_DATA_ERR`;
