const EVENTS_PREFIX = 'EVENTS/';

export const GET_EVENTS = `${EVENTS_PREFIX}GET_EVENTS`;
export const GET_EVENTS_OK = `${EVENTS_PREFIX}GET_EVENTS_OK`;
export const GET_EVENTS_ERR = `${EVENTS_PREFIX}GET_EVENTS_ERR`;

export const UPDATE_EVENT = `${EVENTS_PREFIX}UPDATE_EVENT`;
export const UPDATE_EVENT_OK = `${EVENTS_PREFIX}UPDATE_EVENT_OK`;
export const UPDATE_EVENT_ERR = `${EVENTS_PREFIX}UPDATE_EVENT_ERR`;
