const EVENT_MODAL_PREFIX = 'EVENT_MODAL/';

export const OPEN_EVENT_MODAL = `${EVENT_MODAL_PREFIX}OPEN_EVENT_MODAL`;
export const CLOSE_EVENT_MODAL = `${EVENT_MODAL_PREFIX}CLOSE_EVENT_MODAL`;

export const UPDATE_EVENT_VIA_MODAL = `${EVENT_MODAL_PREFIX}UPDATE_EVENT_VIA_MODAL`;
